tap "heroku/brew"
tap "jhlee0409/tap"

# Homebrew will not load a formula or cask from a third-party tap until it is
# trusted, so the entries from the taps above are marked trusted here.
brew "colima"
brew "deno"
brew "direnv"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "editorconfig"
brew "fish"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "ghq"
brew "heroku/brew/heroku", trusted: true
brew "jq"
brew "mint"
brew "mise"
brew "peco"
brew "pinentry-mac"
brew "terminal-notifier"
brew "tree"
brew "usage"
brew "uv"
brew "wget"

# brew bundle installs casks with --adopt, which takes over apps that were
# installed outside of Homebrew and would otherwise abort the run.
cask "1password"
cask "1password-cli"
cask "android-studio"
cask "chatgpt"
cask "claude"
cask "jhlee0409/tap/claude-code-history-viewer", trusted: true
cask "cleanshot"
cask "cloudflare-warp"
cask "cmux"
cask "codex"
cask "discord"
cask "figma"
cask "firefox"
cask "fork"
cask "gcloud-cli"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "meetingbar"
cask "microsoft-edge"
cask "microsoft-remote-desktop"
cask "minecraft"
cask "miro"
cask "nani"
cask "ngrok"
cask "notion"
cask "poedit"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "xcodes-app"
cask "zoom"
