#!/bin/sh

echo "Instal macos-provisioning"

ZIP_PATH="/tmp/macos-provisioning-master.zip"
TMP_DIR="/tmp/macos-provisioning-master"

cd /tmp
curl -L https://github.com/fujikky/macos-provisioning/archive/master.zip -o macos-provisioning-master.zip
unzip macos-provisioning-master.zip
./macos-provisioning-master/scripts/install.sh

rm -rf $TMP_DIR
echo "Deleted $TMP_DIR"

rm -rf $ZIP_PATH
echo "Deleted $ZIP_PATH"

echo "Start fish session"
/usr/local/bin/fish
